server:
  port: 9090
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/balancegame
      username: balance
      password: balance
      maximum-pool-size: 12
      minimum-idle: 5
      auto-commit: true
    url: jdbc:postgresql://127.0.0.1:5432/balancegame
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true